export { default as burger } from './burger.jpg'
export { default as pizza } from './pizza.jpg'
export { default as appetizers } from './appetizers.jpg'
export {default as asian} from './asian.jpg'
export {default as beef} from './beef.jpg'
export {default as breakfast} from './breakfast.jpg'
export {default as chicken} from './chicken.jpg'
export {default as dessert} from './dessert.jpg'
export {default as drinks} from './drinks.jpg'
export {default as gluten} from './gluten.jpg'
export {default as indian } from './indian.jpg'
export {default as lesscarbs} from './less-carbs.jpg'
export {default as mex} from './mex.jpg'
export {default as pasta} from './pasta.jpg'
export {default as salad} from './salad.jpg'
export {default as sandwich} from './sandwich.jpg'
export {default as seafood} from './seafood.jpg'
export {default as soup} from './soup.jpg'
export {default as vegan} from './vegan.jpg'
export {default as vegetarian} from './vegetarian.jpg'